// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDH.infrastructure.Persistence.Data;

#nullable disable

namespace SDH.infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624173938_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDH.Domain.Entities.Operative.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("FullName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Nombre_Completo");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Identificacion_Cliente");

                    b.Property<int>("IdentificationType")
                        .HasColumnType("int")
                        .HasColumnName("Id_Tipo_Identificacion");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Anonimizado");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Aprobado");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Eliminado");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Verificado");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Modificacion");

                    b.Property<DateTime?>("LegalExpirationDate")
                        .HasColumnType("Date")
                        .HasColumnName("Fecha_Expiracion_Legal");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_Cliente_Nombre")
                        .HasFilter("[Esta_Eliminado] = 0 AND [Esta_Anonimizado] = 0");

                    b.HasIndex("Identification")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente_Identificacion")
                        .HasFilter("[Esta_Eliminado] = 0 AND [Esta_Anonimizado] = 0");

                    b.HasIndex("IdentificationType");

                    b.ToTable("Tbl_Maest_Cliente", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.ClientFinancial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Financiero_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AccountingAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto_Contable");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Tipo_Contabilidad");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_FinancieroCliente_TipoContabilidad");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("IX_FinancieroCliente_IdCliente");

                    b.ToTable("Tbl_Financiero_cliente", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.CoreOfficializations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Oficializacion_Core");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    b.Property<string>("CoreResponseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Respuesta_Core_Codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("SentJsonPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Trama_Json_Enviada");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_OficializacionCore_IdCliente");

                    b.HasIndex("CoreResponseCode")
                        .HasDatabaseName("IX_OficializacionCore_RespuestaCoreCodigo");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_OficializacionCore_FechaCreacion");

                    b.ToTable("Tbl_Oficializacion_Core", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.CustomerAddresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Direccion_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Tipo_Direccion");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Aprobacion");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Aprobador");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ciudad");

                    b.Property<string>("CityCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Codigo_Ciudad");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Pais");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Codigo_Pais");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Direccion_Completa");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Eliminado");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("Es_Principal");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Modificacion");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)")
                        .HasColumnName("Latitud");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)")
                        .HasColumnName("Longitud");

                    b.Property<string>("LopdpStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_LOPDP");

                    b.Property<string>("Parish")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Parroquia");

                    b.Property<string>("ParishCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Codigo_Parroquia");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Codigo_Postal");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Provincia");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Codigo_Provincia");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Source_Direccion");

                    b.Property<int?>("VerificationStatusId")
                        .HasColumnType("int")
                        .HasColumnName("Estado_Verificacion");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Verificacion");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Verificador");

                    b.HasKey("Id");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("VerificationStatusId");

                    b.HasIndex("ClientId", "IsDeleted")
                        .HasDatabaseName("IX_Contacto_Cliente_IdCliente_EstaEliminado");

                    b.HasIndex("ClientId", "IsPrimary")
                        .HasDatabaseName("IX_Direccion_Cliente_IdCliente");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ClientId", "IsPrimary"), new[] { "FullAddress", "City", "Latitude", "Longitude" });

                    b.ToTable("Tbl_Direccion_Cliente", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.CustomerContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Contacto_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    b.Property<int>("ContactMediumTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Tipo_Contacto");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Valor_Contacto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Eliminado");

                    b.Property<int>("LOPDPStatusId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Estado_LOPDP");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Modificacion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Source");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Verificacion");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Verificador");

                    b.Property<int>("VerifyStatusId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Estado_Verificacion");

                    b.HasKey("Id");

                    b.HasIndex("ContactMediumTypeId");

                    b.HasIndex("ContactValue")
                        .HasDatabaseName("IX_Contacto_Cliente_Valor");

                    b.HasIndex("LOPDPStatusId");

                    b.HasIndex("VerifyStatusId")
                        .HasDatabaseName("IX_ContactoCliente_EstadoVerificacion");

                    b.HasIndex("ClientId", "IsDeleted")
                        .HasDatabaseName("IX_ContactoCliente_IdCliente_EstaEliminado");

                    b.HasIndex("ClientId", "VerifyStatusId", "ContactMediumTypeId")
                        .HasDatabaseName("IX_Contacto_Cliente_Performance_Query")
                        .HasFilter("[Esta_Eliminado] = 0");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ClientId", "VerifyStatusId", "ContactMediumTypeId"), new[] { "ContactValue", "IsDeleted" });

                    b.ToTable("Tbl_Contacto_Cliente", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Parametro.CatalogGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Grupo_Catalogo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Creacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Grupo");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Es_Sistema");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Modificacion");

                    b.HasKey("Id");

                    b.HasIndex("GroupName")
                        .IsUnique()
                        .HasDatabaseName("UQ_GrupoCatalogo_NombreGrupo");

                    b.ToTable("Tbl_Cat_Grupo", "parametro");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Parametro.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id_Item_Catalogo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Creacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Texto_Visual");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("Orden_Visual");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Grupo_Catalogo");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Esta_Activo");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Modificacion");

                    b.Property<string>("ValueCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Codigo_Valor");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "IsActive")
                        .HasDatabaseName("IX_ItemCatalogo_Buscador");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("GroupId", "IsActive"), new[] { "ValueCode", "DisplayName", "DisplayOrder" });

                    b.HasIndex("GroupId", "ValueCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_ItemCatalogo_IdGrupoCatalogo_CodigoValor");

                    b.ToTable("Tbl_Cat_Item", "parametro");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Seguridad.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre_Asesor");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Activo");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Eliminado");

                    b.Property<bool?>("IsLockedOut")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Bloqueado");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Ultimo_Acceso");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Modificacion");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Clave_Hash");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rol_Sistema");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Codigo_Usuario");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuario_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Usuario_EstaActivo");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuario_CodigoUsuario");

                    b.ToTable("Tbl_Maest_Usuario", "seguridad");
                });

            modelBuilder.Entity("SDH.Infrastructure.Persistence.ReadModels.Parametro.VwCatalogoDetalle", b =>
                {
                    b.Property<string>("CodigoValor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Codigo_Valor");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("bit")
                        .HasColumnName("Es_Sistema");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Activo");

                    b.Property<int>("IdGrupoCatalogo")
                        .HasColumnType("int")
                        .HasColumnName("Id_Grupo_Catalogo");

                    b.Property<int>("IdItemCatalogo")
                        .HasColumnType("int")
                        .HasColumnName("Id_Item_Catalogo");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre_Grupo");

                    b.Property<int>("OrdenVisual")
                        .HasColumnType("int")
                        .HasColumnName("Orden_Visual");

                    b.Property<string>("TextoVisual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Texto_Visual");

                    b.ToTable((string)null);

                    b.ToView("Vw_Cat_Detalle_General", "parametro");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.Client", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Parametro.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("IdentificationType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_TipoIdentificacion");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.ClientFinancial", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Operative.Client", null)
                        .WithMany("Financials")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Financiero");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.CoreOfficializations", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Operative.Client", null)
                        .WithMany("Officializations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Oficializacion");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.CustomerAddresses", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Parametro.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Direccion_Cliente_Tipo_Direccion");

                    b.HasOne("SDH.Domain.Entities.Operative.Client", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Direccion");

                    b.HasOne("SDH.Domain.Entities.Parametro.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("VerificationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Direccion_Cliente_Estado_verificacion");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.CustomerContacts", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Operative.Client", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Contacto");

                    b.HasOne("SDH.Domain.Entities.Parametro.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ContactMediumTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contacto_Cliente_TipoMedioContacto");

                    b.HasOne("SDH.Domain.Entities.Parametro.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("LOPDPStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contacto_Cliente_EstadoLOPDP");

                    b.HasOne("SDH.Domain.Entities.Parametro.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("VerifyStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contacto_Cliente_EstadoVerificado");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Parametro.CatalogItem", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Parametro.CatalogGroup", null)
                        .WithMany("Items")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Grupo_Item");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("Financials");

                    b.Navigation("Officializations");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Parametro.CatalogGroup", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
