// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDH.infrastructure.Persistence.Data;

#nullable disable

namespace SDH.infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDH.Domain.Entities.Operative.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("FullName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Nombre_Completo");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Identificacion_Cliente");

                    b.Property<int>("IdentificationType")
                        .HasColumnType("int")
                        .HasColumnName("Id_Tipo_Identificacion");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Anonimizado");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Aprobado");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Eliminado");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Verificado");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Modificacion");

                    b.Property<DateTime?>("LegalExpirationDate")
                        .HasColumnType("Date")
                        .HasColumnName("Fecha_Expiracion_Legal");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_Cliente_Nombre")
                        .HasFilter("[Esta_Eliminado] = 0 AND [Esta_Anonimizado] = 0");

                    b.HasIndex("Identification")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente_Identificacion")
                        .HasFilter("[Esta_Eliminado] = 0 AND [Esta_Anonimizado] = 0");

                    b.HasIndex("IdentificationType");

                    b.ToTable("Tbl_Maest_Cliente", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.ContactoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Contacto_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Eliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Verificacion");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    b.Property<int>("IdContactMediumType")
                        .HasColumnType("int")
                        .HasColumnName("Id_Tipo_Contacto");

                    b.Property<int>("IdLOPDPStatus")
                        .HasColumnType("int")
                        .HasColumnName("Id_Estado_LOPDP");

                    b.Property<int>("IdVerifyStatus")
                        .HasColumnType("int")
                        .HasColumnName("Id_Estado_Verificacion");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Modificacion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Source");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("UsuarioVerificador")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Verificador");

                    b.Property<string>("ValorContacto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Valor_Contacto");

                    b.HasKey("Id");

                    b.HasIndex("IdContactMediumType");

                    b.HasIndex("IdLOPDPStatus");

                    b.HasIndex("IdVerifyStatus")
                        .HasDatabaseName("IX_ContactoCliente_EstadoVerificacion");

                    b.HasIndex("ValorContacto")
                        .HasDatabaseName("IX_Contacto_Cliente_Valor");

                    b.HasIndex("IdCliente", "EstaEliminado")
                        .HasDatabaseName("IX_ContactoCliente_IdCliente_EstaEliminado");

                    b.HasIndex("IdCliente", "IdVerifyStatus", "IdContactMediumType")
                        .HasDatabaseName("IX_Contacto_Cliente_Performance_Query")
                        .HasFilter("[Esta_Eliminado] = 0");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("IdCliente", "IdVerifyStatus", "IdContactMediumType"), new[] { "ValorContacto", "EstaEliminado" });

                    b.ToTable("Tbl_Contacto_Cliente", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.DireccionCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Direccion_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ciudad");

                    b.Property<string>("CodigoCiudad")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Codigo_Ciudad");

                    b.Property<string>("CodigoPais")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Codigo_Pais");

                    b.Property<string>("CodigoParroquia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Codigo_Parroquia");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Codigo_Postal");

                    b.Property<string>("CodigoProvincia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Codigo_Provincia");

                    b.Property<string>("DireccionCompleta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Direccion_Completa");

                    b.Property<bool?>("EsPrincipal")
                        .HasColumnType("bit")
                        .HasColumnName("Es_Principal");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Eliminado");

                    b.Property<string>("EstadoLOPDP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_LOPDP");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Aprobacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Verificacion");

                    b.Property<int?>("IdAddressType")
                        .HasColumnType("int")
                        .HasColumnName("Id_Tipo_Direccion");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    b.Property<int?>("IdVerificationStatus")
                        .HasColumnType("int")
                        .HasColumnName("Estado_Verificacion");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Modificacion");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)")
                        .HasColumnName("Latitud");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)")
                        .HasColumnName("Longitud");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Pais");

                    b.Property<string>("Parroquia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Parroquia");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Provincia");

                    b.Property<string>("SourceDireccion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Source_Direccion");

                    b.Property<string>("UsuarioAprobador")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Aprobador");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("UsuarioVerificador")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Verificador");

                    b.HasKey("Id");

                    b.HasIndex("IdAddressType");

                    b.HasIndex("IdVerificationStatus");

                    b.HasIndex("Id", "EsPrincipal")
                        .HasDatabaseName("IX_Direccion_Cliente_IdCliente");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id", "EsPrincipal"), new[] { "DireccionCompleta", "Ciudad", "Latitud", "Longitud" });

                    b.HasIndex("IdCliente", "EstaEliminado")
                        .HasDatabaseName("IX_ContactoCliente_IdCliente_EstaEliminado");

                    b.ToTable("Tbl_Direccion_Cliente", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.FinancieroCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Financiero_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    b.Property<decimal>("MontoContable")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto_Contable");

                    b.Property<string>("TipoContabilidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Tipo_Contabilidad");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("IX_FinancieroCliente_IdCliente");

                    b.HasIndex("TipoContabilidad")
                        .HasDatabaseName("IX_FinancieroCliente_TipoContabilidad");

                    b.ToTable("Tbl_Financiero_cliente", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.OficializacionCore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Oficializacion_Core");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Cliente");

                    b.Property<string>("RespuestaCoreCodigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Respuesta_Core_Codigo");

                    b.Property<string>("TramaJsonEnviada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Trama_Json_Enviada");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario_Creacion");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_OficializacionCore_FechaCreacion");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("IX_OficializacionCore_IdCliente");

                    b.HasIndex("RespuestaCoreCodigo")
                        .HasDatabaseName("IX_OficializacionCore_RespuestaCoreCodigo");

                    b.ToTable("Tbl_Oficializacion_Core", "operativo");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Parametro.GrupoCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Grupo_Catalogo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("EsSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Es_Sistema");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Creacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Grupo");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Modificacion");

                    b.HasKey("Id");

                    b.HasIndex("NombreGrupo")
                        .IsUnique()
                        .HasDatabaseName("UQ_GrupoCatalogo_NombreGrupo");

                    b.ToTable("Tbl_Cat_Grupo", "parametro");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Parametro.ItemCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id_Item_Catalogo");

                    b.Property<string>("CodigoValor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Codigo_Valor");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Esta_Activo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Creacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<int>("IdGrupoCatalogo")
                        .HasColumnType("int")
                        .HasColumnName("Id_Grupo_Catalogo");

                    b.Property<int>("OrdenVisual")
                        .HasColumnType("int")
                        .HasColumnName("Orden_Visual");

                    b.Property<string>("TextoVisual")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Texto_Visual");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Modificacion");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupoCatalogo", "CodigoValor")
                        .IsUnique()
                        .HasDatabaseName("UQ_ItemCatalogo_IdGrupoCatalogo_CodigoValor");

                    b.HasIndex("IdGrupoCatalogo", "EstaActivo")
                        .HasDatabaseName("IX_ItemCatalogo_Buscador");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("IdGrupoCatalogo", "EstaActivo"), new[] { "CodigoValor", "TextoVisual", "OrdenVisual" });

                    b.ToTable("Tbl_Cat_Item", "parametro");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Clave_Hash");

                    b.Property<string>("CodigoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Codigo_Usuario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Activo");

                    b.Property<bool?>("EstaBloqueado")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Bloqueado");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Eliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Modificacion");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Fecha_Ultimo_Acceso");

                    b.Property<string>("NombreAsesor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre_Asesor");

                    b.Property<string>("RolSistema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rol_Sistema");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario_Modificacion");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuario_CodigoUsuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuario_Email");

                    b.HasIndex("EstaActivo")
                        .HasDatabaseName("IX_Usuario_EstaActivo");

                    b.ToTable("Tbl_Maest_Usuario", "seguridad");
                });

            modelBuilder.Entity("SDH.Infrastructure.Persistence.ReadModels.Parametro.VwCatalogoDetalle", b =>
                {
                    b.Property<string>("CodigoValor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Codigo_Valor");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("bit")
                        .HasColumnName("Es_Sistema");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Esta_Activo");

                    b.Property<int>("IdGrupoCatalogo")
                        .HasColumnType("int")
                        .HasColumnName("Id_Grupo_Catalogo");

                    b.Property<long>("IdItemCatalogo")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Item_Catalogo");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre_Grupo");

                    b.Property<int>("OrdenVisual")
                        .HasColumnType("int")
                        .HasColumnName("Orden_Visual");

                    b.Property<string>("TextoVisual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Texto_Visual");

                    b.ToTable((string)null);

                    b.ToView("Vw_Cat_Detalle_General", "parametro");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.Client", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Parametro.ItemCatalogo", null)
                        .WithMany()
                        .HasForeignKey("IdentificationType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_TipoIdentificacion");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.ContactoCliente", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Operative.Client", null)
                        .WithMany("Contacts")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Contacto");

                    b.HasOne("SDH.Domain.Entities.Parametro.ItemCatalogo", null)
                        .WithMany()
                        .HasForeignKey("IdContactMediumType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contacto_Cliente_TipoMedioContacto");

                    b.HasOne("SDH.Domain.Entities.Parametro.ItemCatalogo", null)
                        .WithMany()
                        .HasForeignKey("IdLOPDPStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contacto_Cliente_EstadoLOPDP");

                    b.HasOne("SDH.Domain.Entities.Parametro.ItemCatalogo", null)
                        .WithMany()
                        .HasForeignKey("IdVerifyStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contacto_Cliente_EstadoVerificado");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.DireccionCliente", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Parametro.ItemCatalogo", null)
                        .WithMany()
                        .HasForeignKey("IdAddressType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Direccion_Cliente_Tipo_Direccion");

                    b.HasOne("SDH.Domain.Entities.Operative.Client", null)
                        .WithMany("Addresses")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Direccion");

                    b.HasOne("SDH.Domain.Entities.Parametro.ItemCatalogo", null)
                        .WithMany()
                        .HasForeignKey("IdVerificationStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Direccion_Cliente_Estado_verificacion");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.FinancieroCliente", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Operative.Client", null)
                        .WithMany("Financials")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Financiero");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.OficializacionCore", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Operative.Client", null)
                        .WithMany("Officializations")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Oficializacion");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Parametro.ItemCatalogo", b =>
                {
                    b.HasOne("SDH.Domain.Entities.Parametro.GrupoCatalogo", null)
                        .WithMany("Items")
                        .HasForeignKey("IdGrupoCatalogo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Grupo_Item");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Operative.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("Financials");

                    b.Navigation("Officializations");
                });

            modelBuilder.Entity("SDH.Domain.Entities.Parametro.GrupoCatalogo", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
